version: '3.3'

services:
  postgres:
    container_name: postgres
    image: postgres:14.1
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
    # environment:
    #   POSTGRES_USER: user_jubelio
    #   POSTGRES_PASSWORD: pass_jubelio
    #   POSTGRES_DB: jubelio
    ports:
      - 5432:5432